### ISSUE TITLE
fuego: command not found

### ISSUE THREAD

**Issue by hoadq-1371** [sgarciac/fuego#14]
i follow by steps:

> git clone https://github.com/sgarciac/fuego.git
> cd fuego
> go build .
> ./fuego --help

but when i run 
> fuego collections

then error log fuego: command not found. How can I fix it

![Screenshot from 2019-12-04 13-49-26](https://user-images.githubusercontent.com/49504864/70119749-9133f780-169d-11ea-8cd8-7a465b517571.png)

**Comment by sgarciac** [comment]
Notice that you are writing ```fuego collections``` instead of ```./fuego collections```. I assume ~/Project/Golang/fuego is not in your PATH, so your shell won't find fuego just by calling "fuego".

You'll probably want to do a ```go install .``` to have fuego installed inside your GOPATH directory (which is ~/go by default). Please see the go documentation if you need more details.
