### ISSUE TITLE
The flag --merge of the set command does not work

### ISSUE THREAD

**Issue by ticketapp** [sgarciac/fuego#19]
The following command (directly taken from the doc) 
`fuego set --merge Msg_Conversation 8ec617d5-37d4-4841-9678-a22939cf8638 '{"messageCount": 1}'`
leads to this error:
`Incorrect Usage: flag provided but not defined: -merge`

(whithout the --merge flag it set and does not update the database entry)

By the way, thanks for this repo, it's incredibly helpful and usually works great :)

**Comment by eqinox76** [comment]
Glad that the tool helps you too1 Thanks @sgarciac !

Your bug sounds a bit odd. Are you sure that you have the most recent version? You should see the following:
```
$ fuego set --help
NAME:
   fuego set - Set the contents of a document

USAGE:
   fuego set [command options] collection-path document-id json-document

OPTIONS:
   --timestamp, --ts  treat strings values that match rfc3339 as timestamps
   --merge            if set the set operation will do a update/patch
```

If not check that your $GOPATH/src/github.com/sgarciac/fuego is up to date.
`go get -u github.com/sgarciac/fuego` may help. When the source is up to date compile locally or reinstall via `go install github.com/sgarciac/fuego`. That should fix it or at least give an idea where the issue is.

**Comment by sgarciac** [comment]
@ticketapp : There was a bit of a delay between @eqinox76 adding support for merge and me creating a new release, so you perhaps have an older version. Please let us know!

**Comment by ticketapp** [comment]
Thanks to both of you, you were right: I had an outdated version (I did not think about it since I used it for the first time something like one month ago).

Have a good day
