### ISSUE TITLE
GeoPoint data type not supported

### ISSUE THREAD

**Issue by Shailevy** [sgarciac/fuego#24]
If I save a document with GeoPints data type to a JSON and then I reload it then the new data have 'latitude' and 'longitude' fields instead od GeoPoints

**Comment by sgarciac** [comment]
As usual, I somehow failed to see this issue in time, sorry about the hude delay.
 
Unfortunately, since we are using json as the format for feeding data to firestore, we are somewhat constrained by json primitive types. We could do something like what we do for timestamps, tho, for example, passing a flag to tell fuego to handle any object of the form {latitude: <number>, longiture: <number>} as a geopoint.

**Comment by sgarciac** [comment]
I will provide a description of the task for anyone coming for hacktoberfest points

**Comment by sgarciac** [comment]
0.20.0 now supports geopoints.
