### ISSUE TITLE
Delete command missing recursive option

### ISSUE THREAD

**Issue by sgarciac** [sgarciac/fuego#59]
The delete command should support an option to delete subcollections recursively

**Comment by loomchild** [comment]
Firebase CLI supports recursive delete: https://github.com/firebase/firebase-tools#cloud-firestore-commands, https://firebase.google.com/docs/firestore/solutions/delete-collections (Node.js implementation, not sure about Go).

**Comment by sgarciac** [comment]
Yes, unless I am wrong the recursion is directly written in the firebase CLI tool and not supported by the underlying nodejs library.

**Comment by loomchild** [comment]
I think so by quickly looking at: https://github.com/firebase/firebase-tools/blob/3970dda2bfc5d27a85ac6ac949ef925730cba2b1/src/firestore/delete.ts. 

IMHO, if the recursive delete is already supported by the CLI, there's no urgent need to implement it in Fuego. (although it would be a cool addition, especially since you already have recursive copy)

**Comment by Mopsgeschwindigkeit** [comment]
I guess this issue can be closed :)
